#!/bin/bash
#PBS -N SEAsia
#PBS -l select=21
#PBS -l walltime=02:00:00
#PBS -A n01-ACCORD
# mail alert at (b)eginning, (e)nd and (a)bortion of execution
#PBS -m bea
#PBS -M jelt@noc.ac.uk

module swap PrgEnv-cray PrgEnv-intel
module load cray-netcdf-hdf5parallel
module load cray-hdf5-parallel

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
#  echo $(readlink -f $PBS_O_WORKDIR)
# export OMP_NUM_THREADS=1

cd $PBS_O_WORKDIR
#
  echo " ";
  OCEANCORES=480 #92
  XIOSCORES=4
ulimit -c unlimited
ulimit -s unlimited

rm -f core

aprun -b -n $XIOSCORES -N 4 ./xios_server.exe : -n $OCEANCORES -N 24 ./opa

exit
