#!/bin/bash
#PBS -N SEAsia
#PBS -l select=5
#PBS -l walltime=03:00:00
#PBS -A n01-ACCORD
# mail alert at (b)eginning, (e)nd and (a)bortion of execution

export PBS_O_WORKDIR=$(readlink -f $PBS_O_WORKDIR)
#  echo $(readlink -f $PBS_O_WORKDIR)
# export OMP_NUM_THREADS=1

cd $PBS_O_WORKDIR
#
  echo " ";
## run on standard queue
#  OCEANCORES=92
#  XIOSCORES=5
## will fit on short queue
  OCEANCORES=88
  XIOSCORES=4
ulimit -c unlimited
ulimit -s unlimited

rm -f core
## run standard queue
#aprun -b -n $XIOSCORES -N 5 ./xios_server.exe : -n $OCEANCORES -N 24 ./opa
## Will fit on short queue
aprun -b -n $XIOSCORES -N 4 ./xios_server.exe : -n $OCEANCORES -N 24 ./opa_currentv2

exit
