#!/bin/bash

year=$1
rdt=$2
ndt=0
day=86400

for y in $( seq 1970 $year )
do

rem1=$((y%4))
rem2=$((y%100))
rem3=$((y%400))

if [ ${rem3} = "0" ]
then
       ntstp=$(( 366 * $day / $rdt )) 
elif [ ${rem2} = "0" -a ${rem3} != "0" ]
then
       ntstp=$(( 365 * $day / $rdt ))
elif [ ${rem1} = "0" -a ${rem2} != "0" ]
then
       ntstp=$(( 366 * $day / $rdt )) 
else
       ntstp=$(( 365 * $day / $rdt ))
fi
 
ndt=$(( $ndt + $ntstp ))

done

echo $ndt

